/*
 *	autogen/server/chat/ChatMessage.cpp generated by engine3 IDL compiler 0.70
 */

#include "ChatMessage.h"

/*
 *	ChatMessageStub
 */

enum {RPC_SETSTRING__STRING_ = 3293646548,RPC_TOSTRING__};

ChatMessage::ChatMessage() : ManagedObject(DummyConstructorParameter::instance()) {
	ChatMessageImplementation* _implementation = new ChatMessageImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ChatMessage");
}

ChatMessage::ChatMessage(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("ChatMessage");
}

ChatMessage::~ChatMessage() {
}



void ChatMessage::setString(const String& msg) {
	ChatMessageImplementation* _implementation = static_cast<ChatMessageImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSTRING__STRING_);
		method.addAsciiParameter(msg);

		method.executeWithVoidReturn();
	} else {
		_implementation->setString(msg);
	}
}

String ChatMessage::toString() {
	ChatMessageImplementation* _implementation = static_cast<ChatMessageImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_TOSTRING__);

		String _return_toString;
		method.executeWithAsciiReturn(_return_toString);
		return _return_toString;
	} else {
		return _implementation->toString();
	}
}

DistributedObjectServant* ChatMessage::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ChatMessage::_getImplementationForRead() const {
	return _impl;
}

void ChatMessage::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ChatMessageImplementation
 */

ChatMessageImplementation::ChatMessageImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ChatMessageImplementation::~ChatMessageImplementation() {
}


void ChatMessageImplementation::finalize() {
}

void ChatMessageImplementation::_initializeImplementation() {
	_setClassHelper(ChatMessageHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ChatMessageImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ChatMessage*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ChatMessageImplementation::_getStub() {
	return _this.get();
}

ChatMessageImplementation::operator const ChatMessage*() {
	return _this.get();
}

void ChatMessageImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ChatMessageImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ChatMessageImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ChatMessageImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ChatMessageImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ChatMessageImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ChatMessageImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ChatMessageImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("ChatMessage");

}

void ChatMessageImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ChatMessageImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ChatMessageImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xbd8f57ac: //ChatMessage.message
		TypeInfo<String >::parseFromBinaryStream(&message, stream);
		return true;

	}

	return false;
}

void ChatMessageImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ChatMessageImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ChatMessageImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xbd8f57ac; //ChatMessage.message
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&message, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void ChatMessageImplementation::writeJSON(nlohmann::json& j) {
	ManagedObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["message"] = message;

	j["ChatMessage"] = thisObject;
}

ChatMessageImplementation::ChatMessageImplementation() {
	_initializeImplementation();
	// server/chat/ChatMessage.idl():  		message = "";
	message = "";
}

void ChatMessageImplementation::setString(const String& msg) {
	// server/chat/ChatMessage.idl():  		message = msg;
	message = msg;
}

String ChatMessageImplementation::toString() {
	// server/chat/ChatMessage.idl():  		return message;
	return message;
}

/*
 *	ChatMessageAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ChatMessageAdapter::ChatMessageAdapter(ChatMessage* obj) : ManagedObjectAdapter(obj) {
}

void ChatMessageAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_SETSTRING__STRING_:
		{
			 String msg; inv->getAsciiParameter(msg);
			
			setString(msg);
			
		}
		break;
	case RPC_TOSTRING__:
		{
			
			String _m_res = toString();
			resp->insertAscii(_m_res);
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

void ChatMessageAdapter::setString(const String& msg) {
	(static_cast<ChatMessage*>(stub))->setString(msg);
}

String ChatMessageAdapter::toString() {
	return (static_cast<ChatMessage*>(stub))->toString();
}

/*
 *	ChatMessageHelper
 */

ChatMessageHelper* ChatMessageHelper::staticInitializer = ChatMessageHelper::instance();

ChatMessageHelper::ChatMessageHelper() {
	className = "ChatMessage";

	Core::getObjectBroker()->registerClass(className, this);
}

void ChatMessageHelper::finalizeHelper() {
	ChatMessageHelper::finalize();
}

DistributedObject* ChatMessageHelper::instantiateObject() {
	return new ChatMessage(DummyConstructorParameter::instance());
}

DistributedObjectServant* ChatMessageHelper::instantiateServant() {
	return new ChatMessageImplementation();
}

DistributedObjectPOD* ChatMessageHelper::instantiatePOD() {
	return new ChatMessagePOD();
}

DistributedObjectAdapter* ChatMessageHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ChatMessageAdapter(static_cast<ChatMessage*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ChatMessagePOD
 */

ChatMessagePOD::~ChatMessagePOD() {
}

ChatMessagePOD::ChatMessagePOD(void) {
	_className = "ChatMessage";
}


void ChatMessagePOD::writeJSON(nlohmann::json& j) {
	ManagedObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (message)
		thisObject["message"] = message.value();

	j["ChatMessage"] = thisObject;
}


void ChatMessagePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ChatMessagePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ChatMessagePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (message) {
	_nameHashCode = 0xbd8f57ac; //ChatMessage.message
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&message.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ChatMessagePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xbd8f57ac: //ChatMessage.message
		{
			String _mnmessage;
			TypeInfo<String >::parseFromBinaryStream(&_mnmessage, stream);
			message = std::move(_mnmessage);
		}
		return true;

	}

	return false;
}

void ChatMessagePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ChatMessagePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ChatMessagePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<String >::toBinaryStream(&message.value(), stream);


}

