/*
 *	autogen/server/zone/objects/mission/MissionObserver.cpp generated by engine3 IDL compiler 0.70
 */

#include "MissionObserver.h"

#include "server/zone/objects/mission/MissionObjective.h"

/*
 *	MissionObserverStub
 */

enum {RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_ = 1471283440,RPC_DESTROYOBJECTFROMDATABASE__};

MissionObserver::MissionObserver(MissionObjective* objective) : Observer(DummyConstructorParameter::instance()) {
	MissionObserverImplementation* _implementation = new MissionObserverImplementation(objective);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("MissionObserver");
}

MissionObserver::MissionObserver(DummyConstructorParameter* param) : Observer(param) {
	_setClassName("MissionObserver");
}

MissionObserver::~MissionObserver() {
}



int MissionObserver::notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2) {
	MissionObserverImplementation* _implementation = static_cast<MissionObserverImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_);
		method.addUnsignedIntParameter(eventType);
		method.addObjectParameter(observable);
		method.addObjectParameter(arg1);
		method.addSignedLongParameter(arg2);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->notifyObserverEvent(eventType, observable, arg1, arg2);
	}
}

void MissionObserver::destroyObjectFromDatabase() {
	MissionObserverImplementation* _implementation = static_cast<MissionObserverImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DESTROYOBJECTFROMDATABASE__);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->destroyObjectFromDatabase();
	}
}

DistributedObjectServant* MissionObserver::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* MissionObserver::_getImplementationForRead() const {
	return _impl;
}

void MissionObserver::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	MissionObserverImplementation
 */

MissionObserverImplementation::MissionObserverImplementation(DummyConstructorParameter* param) : ObserverImplementation(param) {
	_initializeImplementation();
}


MissionObserverImplementation::~MissionObserverImplementation() {
}


void MissionObserverImplementation::finalize() {
}

void MissionObserverImplementation::_initializeImplementation() {
	_setClassHelper(MissionObserverHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void MissionObserverImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<MissionObserver*>(stub);
	ObserverImplementation::_setStub(stub);
}

DistributedObjectStub* MissionObserverImplementation::_getStub() {
	return _this.get();
}

MissionObserverImplementation::operator const MissionObserver*() {
	return _this.get();
}

void MissionObserverImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void MissionObserverImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void MissionObserverImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void MissionObserverImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void MissionObserverImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void MissionObserverImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void MissionObserverImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void MissionObserverImplementation::_serializationHelperMethod() {
	ObserverImplementation::_serializationHelperMethod();

	_setClassName("MissionObserver");

}

void MissionObserverImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(MissionObserverImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool MissionObserverImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ObserverImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa227886d: //MissionObserver.missionObjective
		TypeInfo<ManagedWeakReference<MissionObjective* > >::parseFromBinaryStream(&missionObjective, stream);
		return true;

	}

	return false;
}

void MissionObserverImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = MissionObserverImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int MissionObserverImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ObserverImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xa227886d; //MissionObserver.missionObjective
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<MissionObjective* > >::toBinaryStream(&missionObjective, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void MissionObserverImplementation::writeJSON(nlohmann::json& j) {
	ObserverImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["missionObjective"] = missionObjective;

	j["MissionObserver"] = thisObject;
}

MissionObserverImplementation::MissionObserverImplementation(MissionObjective* objective) {
	_initializeImplementation();
	// server/zone/objects/mission/MissionObserver.idl():  		missionObjective = objective;
	missionObjective = objective;
	// server/zone/objects/mission/MissionObserver.idl():  		Logger.setLoggingName("MissionObserver");
	Logger::setLoggingName("MissionObserver");
}

/*
 *	MissionObserverAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


MissionObserverAdapter::MissionObserverAdapter(MissionObserver* obj) : ObserverAdapter(obj) {
}

void MissionObserverAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_:
		{
			unsigned int eventType = inv->getUnsignedIntParameter();
			Observable* observable = static_cast<Observable*>(inv->getObjectParameter());
			ManagedObject* arg1 = static_cast<ManagedObject*>(inv->getObjectParameter());
			long long arg2 = inv->getSignedLongParameter();
			
			int _m_res = notifyObserverEvent(eventType, observable, arg1, arg2);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_DESTROYOBJECTFROMDATABASE__:
		{
			
			destroyObjectFromDatabase();
			
		}
		break;
	default:
		ObserverAdapter::invokeMethod(methid, inv);
	}
}

int MissionObserverAdapter::notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2) {
	return (static_cast<MissionObserver*>(stub))->notifyObserverEvent(eventType, observable, arg1, arg2);
}

void MissionObserverAdapter::destroyObjectFromDatabase() {
	(static_cast<MissionObserver*>(stub))->destroyObjectFromDatabase();
}

/*
 *	MissionObserverHelper
 */

MissionObserverHelper* MissionObserverHelper::staticInitializer = MissionObserverHelper::instance();

MissionObserverHelper::MissionObserverHelper() {
	className = "MissionObserver";

	Core::getObjectBroker()->registerClass(className, this);
}

void MissionObserverHelper::finalizeHelper() {
	MissionObserverHelper::finalize();
}

DistributedObject* MissionObserverHelper::instantiateObject() {
	return new MissionObserver(DummyConstructorParameter::instance());
}

DistributedObjectServant* MissionObserverHelper::instantiateServant() {
	return new MissionObserverImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* MissionObserverHelper::instantiatePOD() {
	return new MissionObserverPOD();
}

DistributedObjectAdapter* MissionObserverHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new MissionObserverAdapter(static_cast<MissionObserver*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	MissionObserverPOD
 */

MissionObserverPOD::~MissionObserverPOD() {
}

MissionObserverPOD::MissionObserverPOD(void) {
	_className = "MissionObserver";
}


void MissionObserverPOD::writeJSON(nlohmann::json& j) {
	ObserverPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (missionObjective)
		thisObject["missionObjective"] = missionObjective.value();

	j["MissionObserver"] = thisObject;
}


void MissionObserverPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = MissionObserverPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int MissionObserverPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ObserverPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (missionObjective) {
	_nameHashCode = 0xa227886d; //MissionObserver.missionObjective
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<MissionObjectivePOD* > >::toBinaryStream(&missionObjective.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool MissionObserverPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ObserverPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa227886d: //MissionObserver.missionObjective
		{
			ManagedWeakReference<MissionObjectivePOD* > _mnmissionObjective;
			TypeInfo<ManagedWeakReference<MissionObjectivePOD* > >::parseFromBinaryStream(&_mnmissionObjective, stream);
			missionObjective = std::move(_mnmissionObjective);
		}
		return true;

	}

	return false;
}

void MissionObserverPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(MissionObserverPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void MissionObserverPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ObserverPOD::writeObjectCompact(stream);

	TypeInfo<ManagedWeakReference<MissionObjectivePOD* > >::toBinaryStream(&missionObjective.value(), stream);


}

