/*
 *	autogen/server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.cpp generated by engine3 IDL compiler 0.70
 */

#include "SuiBankTransferBox.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	SuiBankTransferBoxStub
 */

enum {RPC_ADDCASH__INT_ = 2418541022,RPC_ADDBANK__INT_,RPC_GETBANK__,RPC_ISBANKTRANSFERBOX__};

SuiBankTransferBox::SuiBankTransferBox(SceneObject* bankObject, CreatureObject* player, unsigned int windowtype) : SuiBox(DummyConstructorParameter::instance()) {
	SuiBankTransferBoxImplementation* _implementation = new SuiBankTransferBoxImplementation(bankObject, player, windowtype);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SuiBankTransferBox");
}

SuiBankTransferBox::SuiBankTransferBox(DummyConstructorParameter* param) : SuiBox(param) {
	_setClassName("SuiBankTransferBox");
}

SuiBankTransferBox::~SuiBankTransferBox() {
}



void SuiBankTransferBox::addCash(int cash) {
	SuiBankTransferBoxImplementation* _implementation = static_cast<SuiBankTransferBoxImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ADDCASH__INT_);
		method.addSignedIntParameter(cash);

		method.executeWithVoidReturn();
	} else {
		_implementation->addCash(cash);
	}
}

void SuiBankTransferBox::addBank(int bank) {
	SuiBankTransferBoxImplementation* _implementation = static_cast<SuiBankTransferBoxImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ADDBANK__INT_);
		method.addSignedIntParameter(bank);

		method.executeWithVoidReturn();
	} else {
		_implementation->addBank(bank);
	}
}

SceneObject* SuiBankTransferBox::getBank() {
	SuiBankTransferBoxImplementation* _implementation = static_cast<SuiBankTransferBoxImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBANK__);

		return static_cast<SceneObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->getBank();
	}
}

BaseMessage* SuiBankTransferBox::generateMessage() {
	SuiBankTransferBoxImplementation* _implementation = static_cast<SuiBankTransferBoxImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->generateMessage();
	}
}

bool SuiBankTransferBox::isBankTransferBox() {
	SuiBankTransferBoxImplementation* _implementation = static_cast<SuiBankTransferBoxImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISBANKTRANSFERBOX__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isBankTransferBox();
	}
}

DistributedObjectServant* SuiBankTransferBox::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SuiBankTransferBox::_getImplementationForRead() const {
	return _impl;
}

void SuiBankTransferBox::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SuiBankTransferBoxImplementation
 */

SuiBankTransferBoxImplementation::SuiBankTransferBoxImplementation(DummyConstructorParameter* param) : SuiBoxImplementation(param) {
	_initializeImplementation();
}


SuiBankTransferBoxImplementation::~SuiBankTransferBoxImplementation() {
}


void SuiBankTransferBoxImplementation::finalize() {
}

void SuiBankTransferBoxImplementation::_initializeImplementation() {
	_setClassHelper(SuiBankTransferBoxHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SuiBankTransferBoxImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SuiBankTransferBox*>(stub);
	SuiBoxImplementation::_setStub(stub);
}

DistributedObjectStub* SuiBankTransferBoxImplementation::_getStub() {
	return _this.get();
}

SuiBankTransferBoxImplementation::operator const SuiBankTransferBox*() {
	return _this.get();
}

void SuiBankTransferBoxImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SuiBankTransferBoxImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SuiBankTransferBoxImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SuiBankTransferBoxImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SuiBankTransferBoxImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SuiBankTransferBoxImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SuiBankTransferBoxImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SuiBankTransferBoxImplementation::_serializationHelperMethod() {
	SuiBoxImplementation::_serializationHelperMethod();

	_setClassName("SuiBankTransferBox");

}

void SuiBankTransferBoxImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SuiBankTransferBoxImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SuiBankTransferBoxImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SuiBoxImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x30bb1267: //SuiBankTransferBox.lblFrom
		TypeInfo<String >::parseFromBinaryStream(&lblFrom, stream);
		return true;

	case 0x1841d11b: //SuiBankTransferBox.lblStartingFrom
		TypeInfo<String >::parseFromBinaryStream(&lblStartingFrom, stream);
		return true;

	case 0xaf4bad34: //SuiBankTransferBox.lblInputFrom
		TypeInfo<String >::parseFromBinaryStream(&lblInputFrom, stream);
		return true;

	case 0x9ef75b5: //SuiBankTransferBox.lblTo
		TypeInfo<String >::parseFromBinaryStream(&lblTo, stream);
		return true;

	case 0x5f6a9747: //SuiBankTransferBox.lblStartingTo
		TypeInfo<String >::parseFromBinaryStream(&lblStartingTo, stream);
		return true;

	case 0x7e9e484b: //SuiBankTransferBox.lblInputTo
		TypeInfo<String >::parseFromBinaryStream(&lblInputTo, stream);
		return true;

	case 0xb3fe4f2: //SuiBankTransferBox.convertRatioFrom
		TypeInfo<String >::parseFromBinaryStream(&convertRatioFrom, stream);
		return true;

	case 0xef07ab2f: //SuiBankTransferBox.convertRatioTo
		TypeInfo<String >::parseFromBinaryStream(&convertRatioTo, stream);
		return true;

	case 0x2a86ef1e: //SuiBankTransferBox.bank
		TypeInfo<ManagedReference<SceneObject* > >::parseFromBinaryStream(&bank, stream);
		return true;

	}

	return false;
}

void SuiBankTransferBoxImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SuiBankTransferBoxImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SuiBankTransferBoxImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SuiBoxImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x30bb1267; //SuiBankTransferBox.lblFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblFrom, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x1841d11b; //SuiBankTransferBox.lblStartingFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblStartingFrom, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xaf4bad34; //SuiBankTransferBox.lblInputFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblInputFrom, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x9ef75b5; //SuiBankTransferBox.lblTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblTo, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x5f6a9747; //SuiBankTransferBox.lblStartingTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblStartingTo, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7e9e484b; //SuiBankTransferBox.lblInputTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblInputTo, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xb3fe4f2; //SuiBankTransferBox.convertRatioFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&convertRatioFrom, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xef07ab2f; //SuiBankTransferBox.convertRatioTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&convertRatioTo, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x2a86ef1e; //SuiBankTransferBox.bank
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<SceneObject* > >::toBinaryStream(&bank, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

SuiBankTransferBoxImplementation::SuiBankTransferBoxImplementation(SceneObject* bankObject, CreatureObject* player, unsigned int windowtype) : SuiBoxImplementation(player, windowtype, SuiBoxImplementation::BANKTRANSFERBOX) {
	_initializeImplementation();
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		bank = bankObject;
	bank = bankObject;
}

void SuiBankTransferBoxImplementation::addCash(int cash) {
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		lblFrom = "Cash";
	lblFrom = "Cash";
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		lblStartingFrom = String.valueOf(cash);
	lblStartingFrom = String::valueOf(cash);
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		lblInputFrom = lblStartingFrom;
	lblInputFrom = lblStartingFrom;
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		convertRatioFrom = "1";
	convertRatioFrom = "1";
}

void SuiBankTransferBoxImplementation::addBank(int bank) {
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		lblTo = "Bank";
	lblTo = "Bank";
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		lblStartingTo = String.valueOf(bank);
	lblStartingTo = String::valueOf(bank);
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		lblInputTo = lblStartingTo;
	lblInputTo = lblStartingTo;
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		convertRatioTo = "1";
	convertRatioTo = "1";
}

SceneObject* SuiBankTransferBoxImplementation::getBank() {
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		return bank;
	return bank;
}

bool SuiBankTransferBoxImplementation::isBankTransferBox() {
	// server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.idl():  		return true;
	return true;
}

/*
 *	SuiBankTransferBoxAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SuiBankTransferBoxAdapter::SuiBankTransferBoxAdapter(SuiBankTransferBox* obj) : SuiBoxAdapter(obj) {
}

void SuiBankTransferBoxAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_ADDCASH__INT_:
		{
			int cash = inv->getSignedIntParameter();
			
			addCash(cash);
			
		}
		break;
	case RPC_ADDBANK__INT_:
		{
			int bank = inv->getSignedIntParameter();
			
			addBank(bank);
			
		}
		break;
	case RPC_GETBANK__:
		{
			
			DistributedObject* _m_res = getBank();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_ISBANKTRANSFERBOX__:
		{
			
			bool _m_res = isBankTransferBox();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		SuiBoxAdapter::invokeMethod(methid, inv);
	}
}

void SuiBankTransferBoxAdapter::addCash(int cash) {
	(static_cast<SuiBankTransferBox*>(stub))->addCash(cash);
}

void SuiBankTransferBoxAdapter::addBank(int bank) {
	(static_cast<SuiBankTransferBox*>(stub))->addBank(bank);
}

SceneObject* SuiBankTransferBoxAdapter::getBank() {
	return (static_cast<SuiBankTransferBox*>(stub))->getBank();
}

bool SuiBankTransferBoxAdapter::isBankTransferBox() {
	return (static_cast<SuiBankTransferBox*>(stub))->isBankTransferBox();
}

/*
 *	SuiBankTransferBoxHelper
 */

SuiBankTransferBoxHelper* SuiBankTransferBoxHelper::staticInitializer = SuiBankTransferBoxHelper::instance();

SuiBankTransferBoxHelper::SuiBankTransferBoxHelper() {
	className = "SuiBankTransferBox";

	Core::getObjectBroker()->registerClass(className, this);
}

void SuiBankTransferBoxHelper::finalizeHelper() {
	SuiBankTransferBoxHelper::finalize();
}

DistributedObject* SuiBankTransferBoxHelper::instantiateObject() {
	return new SuiBankTransferBox(DummyConstructorParameter::instance());
}

DistributedObjectServant* SuiBankTransferBoxHelper::instantiateServant() {
	return new SuiBankTransferBoxImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* SuiBankTransferBoxHelper::instantiatePOD() {
	return new SuiBankTransferBoxPOD();
}

DistributedObjectAdapter* SuiBankTransferBoxHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SuiBankTransferBoxAdapter(static_cast<SuiBankTransferBox*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SuiBankTransferBoxPOD
 */

SuiBankTransferBoxPOD::~SuiBankTransferBoxPOD() {
	finalize();
}

SuiBankTransferBoxPOD::SuiBankTransferBoxPOD(void) {
	_className = "SuiBankTransferBox";
}


void SuiBankTransferBoxPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SuiBankTransferBoxPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SuiBankTransferBoxPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SuiBoxPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (lblFrom) {
	_nameHashCode = 0x30bb1267; //SuiBankTransferBox.lblFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblFrom.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (lblStartingFrom) {
	_nameHashCode = 0x1841d11b; //SuiBankTransferBox.lblStartingFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblStartingFrom.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (lblInputFrom) {
	_nameHashCode = 0xaf4bad34; //SuiBankTransferBox.lblInputFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblInputFrom.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (lblTo) {
	_nameHashCode = 0x9ef75b5; //SuiBankTransferBox.lblTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblTo.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (lblStartingTo) {
	_nameHashCode = 0x5f6a9747; //SuiBankTransferBox.lblStartingTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblStartingTo.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (lblInputTo) {
	_nameHashCode = 0x7e9e484b; //SuiBankTransferBox.lblInputTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&lblInputTo.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (convertRatioFrom) {
	_nameHashCode = 0xb3fe4f2; //SuiBankTransferBox.convertRatioFrom
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&convertRatioFrom.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (convertRatioTo) {
	_nameHashCode = 0xef07ab2f; //SuiBankTransferBox.convertRatioTo
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&convertRatioTo.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (bank) {
	_nameHashCode = 0x2a86ef1e; //SuiBankTransferBox.bank
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<SceneObjectPOD* > >::toBinaryStream(&bank.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool SuiBankTransferBoxPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SuiBoxPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x30bb1267: //SuiBankTransferBox.lblFrom
		{
			String _mnlblFrom;
			TypeInfo<String >::parseFromBinaryStream(&_mnlblFrom, stream);
			lblFrom = std::move(_mnlblFrom);
		}
		return true;

	case 0x1841d11b: //SuiBankTransferBox.lblStartingFrom
		{
			String _mnlblStartingFrom;
			TypeInfo<String >::parseFromBinaryStream(&_mnlblStartingFrom, stream);
			lblStartingFrom = std::move(_mnlblStartingFrom);
		}
		return true;

	case 0xaf4bad34: //SuiBankTransferBox.lblInputFrom
		{
			String _mnlblInputFrom;
			TypeInfo<String >::parseFromBinaryStream(&_mnlblInputFrom, stream);
			lblInputFrom = std::move(_mnlblInputFrom);
		}
		return true;

	case 0x9ef75b5: //SuiBankTransferBox.lblTo
		{
			String _mnlblTo;
			TypeInfo<String >::parseFromBinaryStream(&_mnlblTo, stream);
			lblTo = std::move(_mnlblTo);
		}
		return true;

	case 0x5f6a9747: //SuiBankTransferBox.lblStartingTo
		{
			String _mnlblStartingTo;
			TypeInfo<String >::parseFromBinaryStream(&_mnlblStartingTo, stream);
			lblStartingTo = std::move(_mnlblStartingTo);
		}
		return true;

	case 0x7e9e484b: //SuiBankTransferBox.lblInputTo
		{
			String _mnlblInputTo;
			TypeInfo<String >::parseFromBinaryStream(&_mnlblInputTo, stream);
			lblInputTo = std::move(_mnlblInputTo);
		}
		return true;

	case 0xb3fe4f2: //SuiBankTransferBox.convertRatioFrom
		{
			String _mnconvertRatioFrom;
			TypeInfo<String >::parseFromBinaryStream(&_mnconvertRatioFrom, stream);
			convertRatioFrom = std::move(_mnconvertRatioFrom);
		}
		return true;

	case 0xef07ab2f: //SuiBankTransferBox.convertRatioTo
		{
			String _mnconvertRatioTo;
			TypeInfo<String >::parseFromBinaryStream(&_mnconvertRatioTo, stream);
			convertRatioTo = std::move(_mnconvertRatioTo);
		}
		return true;

	case 0x2a86ef1e: //SuiBankTransferBox.bank
		{
			ManagedReference<SceneObjectPOD* > _mnbank;
			TypeInfo<ManagedReference<SceneObjectPOD* > >::parseFromBinaryStream(&_mnbank, stream);
			bank = std::move(_mnbank);
		}
		return true;

	}

	return false;
}

void SuiBankTransferBoxPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SuiBankTransferBoxPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SuiBankTransferBoxPOD::writeObjectCompact(ObjectOutputStream* stream) {
	SuiBoxPOD::writeObjectCompact(stream);

	TypeInfo<String >::toBinaryStream(&lblFrom.value(), stream);

	TypeInfo<String >::toBinaryStream(&lblStartingFrom.value(), stream);

	TypeInfo<String >::toBinaryStream(&lblInputFrom.value(), stream);

	TypeInfo<String >::toBinaryStream(&lblTo.value(), stream);

	TypeInfo<String >::toBinaryStream(&lblStartingTo.value(), stream);

	TypeInfo<String >::toBinaryStream(&lblInputTo.value(), stream);

	TypeInfo<String >::toBinaryStream(&convertRatioFrom.value(), stream);

	TypeInfo<String >::toBinaryStream(&convertRatioTo.value(), stream);

	TypeInfo<ManagedReference<SceneObjectPOD* > >::toBinaryStream(&bank.value(), stream);


}

