/*
 *	autogen/server/zone/objects/tangible/component/dna/DnaComponent.cpp generated by engine3 IDL compiler 0.70
 */

#include "DnaComponent.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

/*
 *	DnaComponentStub
 */

enum {RPC_SETSTATS__INT_INT_INT_INT_INT_INT_INT_INT_INT_INT_ = 3823629738,RPC_SETSPECIALRESIST__INT_,RPC_ISSPECIALRESIST__INT_,RPC_SETCLEVERNESS__INT_,RPC_GETCLEVERNESS__,RPC_SETLEVEL__INT_,RPC_GETLEVEL__,RPC_SETENDURANCE__INT_,RPC_GETENDURANCE__,RPC_SETFIERCENESS__INT_,RPC_GETFIERCENESS__,RPC_SETPOWER__INT_,RPC_GETPOWER__,RPC_SETINTELLECT__INT_,RPC_GETINTELLECT__,RPC_SETCOURAGE__INT_,RPC_GETCOURAGE__,RPC_SETDEPENDENCY__INT_,RPC_GETDEPENDENCY__,RPC_SETDEXTERITY__INT_,RPC_GETDEXTERITY__,RPC_SETFORTITUDE__INT_,RPC_GETFORITITUDE__,RPC_SETHARDINESS__INT_,RPC_GETHARDINESS__,RPC_SETENERGY__FLOAT_,RPC_GETENERGY__,RPC_SETBLAST__FLOAT_,RPC_GETBLAST__,RPC_SETCOLD__FLOAT_,RPC_GETCOLD__,RPC_SETHEAT__FLOAT_,RPC_GETHEAT__,RPC_SETELECTRIC__FLOAT_,RPC_GETELECTRIC__,RPC_SETACID__FLOAT_,RPC_GETACID__,RPC_SETSTUN__FLOAT_,RPC_GETSTUN__,RPC_SETSABER__FLOAT_,RPC_GETSABER__,RPC_SETARMORRATING__INT_,RPC_SETKINETIC__FLOAT_,RPC_GETKINETIC__,RPC_SETSOURCE__STRING_,RPC_SETSPECIALATTACKONE__STRING_,RPC_GETSPECIALATTACKONE__,RPC_SETSPECIALATTACKTWO__STRING_,RPC_GETSPECIALATTACKTWO__,RPC_SETRANGED__BOOL_,RPC_ISRANGED__,RPC_SETQUALITY__INT_,RPC_GETQUALITY__,RPC_INITIALIZETRANSIENTMEMBERS__,RPC_CONVERTSPECIALATTACK__STRING_,RPC_RESISTVALUE__FLOAT_};

DnaComponent::DnaComponent() : Component(DummyConstructorParameter::instance()) {
	DnaComponentImplementation* _implementation = new DnaComponentImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("DnaComponent");
}

DnaComponent::DnaComponent(DummyConstructorParameter* param) : Component(param) {
	_setClassName("DnaComponent");
}

DnaComponent::~DnaComponent() {
}



void DnaComponent::setStats(int cle, int end, int fie, int pow, int ite, int cou, int dep, int dex, int frt, int har) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSTATS__INT_INT_INT_INT_INT_INT_INT_INT_INT_INT_);
		method.addSignedIntParameter(cle);
		method.addSignedIntParameter(end);
		method.addSignedIntParameter(fie);
		method.addSignedIntParameter(pow);
		method.addSignedIntParameter(ite);
		method.addSignedIntParameter(cou);
		method.addSignedIntParameter(dep);
		method.addSignedIntParameter(dex);
		method.addSignedIntParameter(frt);
		method.addSignedIntParameter(har);

		method.executeWithVoidReturn();
	} else {
		_implementation->setStats(cle, end, fie, pow, ite, cou, dep, dex, frt, har);
	}
}

void DnaComponent::setSpecialResist(int type) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSPECIALRESIST__INT_);
		method.addSignedIntParameter(type);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSpecialResist(type);
	}
}

bool DnaComponent::isSpecialResist(int type) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSPECIALRESIST__INT_);
		method.addSignedIntParameter(type);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isSpecialResist(type);
	}
}

void DnaComponent::setCleverness(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCLEVERNESS__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setCleverness(value);
	}
}

int DnaComponent::getCleverness() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCLEVERNESS__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getCleverness();
	}
}

void DnaComponent::setLevel(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETLEVEL__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setLevel(value);
	}
}

int DnaComponent::getLevel() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETLEVEL__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getLevel();
	}
}

void DnaComponent::setEndurance(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETENDURANCE__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setEndurance(value);
	}
}

int DnaComponent::getEndurance() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETENDURANCE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getEndurance();
	}
}

void DnaComponent::setFierceness(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETFIERCENESS__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setFierceness(value);
	}
}

int DnaComponent::getFierceness() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETFIERCENESS__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getFierceness();
	}
}

void DnaComponent::setPower(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETPOWER__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setPower(value);
	}
}

int DnaComponent::getPower() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETPOWER__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getPower();
	}
}

void DnaComponent::setIntellect(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETINTELLECT__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setIntellect(value);
	}
}

int DnaComponent::getIntellect() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETINTELLECT__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getIntellect();
	}
}

void DnaComponent::setCourage(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCOURAGE__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setCourage(value);
	}
}

int DnaComponent::getCourage() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCOURAGE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getCourage();
	}
}

void DnaComponent::setDependency(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETDEPENDENCY__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setDependency(value);
	}
}

int DnaComponent::getDependency() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETDEPENDENCY__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getDependency();
	}
}

void DnaComponent::setDexterity(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETDEXTERITY__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setDexterity(value);
	}
}

int DnaComponent::getDexterity() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETDEXTERITY__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getDexterity();
	}
}

void DnaComponent::setFortitude(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETFORTITUDE__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setFortitude(value);
	}
}

int DnaComponent::getForititude() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETFORITITUDE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getForititude();
	}
}

void DnaComponent::setHardiness(int value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETHARDINESS__INT_);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setHardiness(value);
	}
}

int DnaComponent::getHardiness() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETHARDINESS__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getHardiness();
	}
}

void DnaComponent::setEnergy(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETENERGY__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setEnergy(value);
	}
}

float DnaComponent::getEnergy() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETENERGY__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getEnergy();
	}
}

void DnaComponent::setBlast(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETBLAST__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setBlast(value);
	}
}

float DnaComponent::getBlast() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBLAST__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBlast();
	}
}

void DnaComponent::setCold(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCOLD__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setCold(value);
	}
}

float DnaComponent::getCold() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCOLD__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getCold();
	}
}

void DnaComponent::setHeat(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETHEAT__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setHeat(value);
	}
}

float DnaComponent::getHeat() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETHEAT__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getHeat();
	}
}

void DnaComponent::setElectric(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETELECTRIC__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setElectric(value);
	}
}

float DnaComponent::getElectric() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETELECTRIC__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getElectric();
	}
}

void DnaComponent::setAcid(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETACID__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setAcid(value);
	}
}

float DnaComponent::getAcid() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETACID__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getAcid();
	}
}

void DnaComponent::setStun(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSTUN__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setStun(value);
	}
}

float DnaComponent::getStun() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSTUN__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getStun();
	}
}

void DnaComponent::setSaber(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSABER__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSaber(value);
	}
}

float DnaComponent::getSaber() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSABER__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getSaber();
	}
}

void DnaComponent::setArmorRating(int rating) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETARMORRATING__INT_);
		method.addSignedIntParameter(rating);

		method.executeWithVoidReturn();
	} else {
		_implementation->setArmorRating(rating);
	}
}

void DnaComponent::setKinetic(float value) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETKINETIC__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setKinetic(value);
	}
}

float DnaComponent::getKinetic() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETKINETIC__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getKinetic();
	}
}

void DnaComponent::setSource(const String& src) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSOURCE__STRING_);
		method.addAsciiParameter(src);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSource(src);
	}
}

void DnaComponent::setSpecialAttackOne(const String& atk) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSPECIALATTACKONE__STRING_);
		method.addAsciiParameter(atk);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSpecialAttackOne(atk);
	}
}

String DnaComponent::getSpecialAttackOne() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSPECIALATTACKONE__);

		String _return_getSpecialAttackOne;
		method.executeWithAsciiReturn(_return_getSpecialAttackOne);
		return _return_getSpecialAttackOne;
	} else {
		return _implementation->getSpecialAttackOne();
	}
}

void DnaComponent::setSpecialAttackTwo(const String& atk) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSPECIALATTACKTWO__STRING_);
		method.addAsciiParameter(atk);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSpecialAttackTwo(atk);
	}
}

String DnaComponent::getSpecialAttackTwo() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSPECIALATTACKTWO__);

		String _return_getSpecialAttackTwo;
		method.executeWithAsciiReturn(_return_getSpecialAttackTwo);
		return _return_getSpecialAttackTwo;
	} else {
		return _implementation->getSpecialAttackTwo();
	}
}

void DnaComponent::setRanged(bool b) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETRANGED__BOOL_);
		method.addBooleanParameter(b);

		method.executeWithVoidReturn();
	} else {
		_implementation->setRanged(b);
	}
}

bool DnaComponent::isRanged() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISRANGED__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isRanged();
	}
}

void DnaComponent::setQuality(int qual) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETQUALITY__INT_);
		method.addSignedIntParameter(qual);

		method.executeWithVoidReturn();
	} else {
		_implementation->setQuality(qual);
	}
}

unsigned int DnaComponent::getQuality() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETQUALITY__);

		return method.executeWithUnsignedIntReturn();
	} else {
		return _implementation->getQuality();
	}
}

void DnaComponent::initializeTransientMembers() {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZETRANSIENTMEMBERS__);

		method.executeWithVoidReturn();
	} else {
		_implementation->initializeTransientMembers();
	}
}

void DnaComponent::updateCraftingValues(CraftingValues* values, bool firstUpdate) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->updateCraftingValues(values, firstUpdate);
	}
}

void DnaComponent::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

String DnaComponent::convertSpecialAttack(String& attackName) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CONVERTSPECIALATTACK__STRING_);
		method.addAsciiParameter(attackName);

		String _return_convertSpecialAttack;
		method.executeWithAsciiReturn(_return_convertSpecialAttack);
		return _return_convertSpecialAttack;
	} else {
		return _implementation->convertSpecialAttack(attackName);
	}
}

String DnaComponent::resistValue(float input) {
	DnaComponentImplementation* _implementation = static_cast<DnaComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RESISTVALUE__FLOAT_);
		method.addFloatParameter(input);

		String _return_resistValue;
		method.executeWithAsciiReturn(_return_resistValue);
		return _return_resistValue;
	} else {
		return _implementation->resistValue(input);
	}
}

DistributedObjectServant* DnaComponent::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* DnaComponent::_getImplementationForRead() const {
	return _impl;
}

void DnaComponent::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	DnaComponentImplementation
 */

DnaComponentImplementation::DnaComponentImplementation(DummyConstructorParameter* param) : ComponentImplementation(param) {
	_initializeImplementation();
}


DnaComponentImplementation::~DnaComponentImplementation() {
}


void DnaComponentImplementation::finalize() {
}

void DnaComponentImplementation::_initializeImplementation() {
	_setClassHelper(DnaComponentHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void DnaComponentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<DnaComponent*>(stub);
	ComponentImplementation::_setStub(stub);
}

DistributedObjectStub* DnaComponentImplementation::_getStub() {
	return _this.get();
}

DnaComponentImplementation::operator const DnaComponent*() {
	return _this.get();
}

void DnaComponentImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void DnaComponentImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void DnaComponentImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void DnaComponentImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void DnaComponentImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void DnaComponentImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void DnaComponentImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void DnaComponentImplementation::_serializationHelperMethod() {
	ComponentImplementation::_serializationHelperMethod();

	_setClassName("DnaComponent");

}

void DnaComponentImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DnaComponentImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool DnaComponentImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ComponentImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x537315ca: //DnaComponent.cleverness
		TypeInfo<int >::parseFromBinaryStream(&cleverness, stream);
		return true;

	case 0xf4af7fae: //DnaComponent.endurance
		TypeInfo<int >::parseFromBinaryStream(&endurance, stream);
		return true;

	case 0xf43f9d83: //DnaComponent.fierceness
		TypeInfo<int >::parseFromBinaryStream(&fierceness, stream);
		return true;

	case 0xefc2f678: //DnaComponent.power
		TypeInfo<int >::parseFromBinaryStream(&power, stream);
		return true;

	case 0xa2aa299c: //DnaComponent.intelligence
		TypeInfo<int >::parseFromBinaryStream(&intelligence, stream);
		return true;

	case 0xbf786897: //DnaComponent.courage
		TypeInfo<int >::parseFromBinaryStream(&courage, stream);
		return true;

	case 0x65db69d9: //DnaComponent.dependency
		TypeInfo<int >::parseFromBinaryStream(&dependency, stream);
		return true;

	case 0x3de40934: //DnaComponent.dexterity
		TypeInfo<int >::parseFromBinaryStream(&dexterity, stream);
		return true;

	case 0x8fefaa2b: //DnaComponent.fortitude
		TypeInfo<int >::parseFromBinaryStream(&fortitude, stream);
		return true;

	case 0x4583898d: //DnaComponent.hardiness
		TypeInfo<int >::parseFromBinaryStream(&hardiness, stream);
		return true;

	case 0x7e2ce408: //DnaComponent.source
		TypeInfo<String >::parseFromBinaryStream(&source, stream);
		return true;

	case 0x951debae: //DnaComponent.special1
		TypeInfo<String >::parseFromBinaryStream(&special1, stream);
		return true;

	case 0x985ecd77: //DnaComponent.special2
		TypeInfo<String >::parseFromBinaryStream(&special2, stream);
		return true;

	case 0x2add1d2: //DnaComponent.ranged
		TypeInfo<bool >::parseFromBinaryStream(&ranged, stream);
		return true;

	case 0xe6a04868: //DnaComponent.quality
		TypeInfo<int >::parseFromBinaryStream(&quality, stream);
		return true;

	case 0x82a47260: //DnaComponent.armorRating
		TypeInfo<int >::parseFromBinaryStream(&armorRating, stream);
		return true;

	case 0x73708b36: //DnaComponent.kinResist
		TypeInfo<float >::parseFromBinaryStream(&kinResist, stream);
		return true;

	case 0x9817b856: //DnaComponent.energyResist
		TypeInfo<float >::parseFromBinaryStream(&energyResist, stream);
		return true;

	case 0x3510d3f8: //DnaComponent.blastResist
		TypeInfo<float >::parseFromBinaryStream(&blastResist, stream);
		return true;

	case 0xe82e7169: //DnaComponent.coldResist
		TypeInfo<float >::parseFromBinaryStream(&coldResist, stream);
		return true;

	case 0x17442b7a: //DnaComponent.heatResist
		TypeInfo<float >::parseFromBinaryStream(&heatResist, stream);
		return true;

	case 0x938671cb: //DnaComponent.elecResist
		TypeInfo<float >::parseFromBinaryStream(&elecResist, stream);
		return true;

	case 0x972a1231: //DnaComponent.acidResist
		TypeInfo<float >::parseFromBinaryStream(&acidResist, stream);
		return true;

	case 0x8c896caf: //DnaComponent.stunResist
		TypeInfo<float >::parseFromBinaryStream(&stunResist, stream);
		return true;

	case 0x37c50636: //DnaComponent.saberResist
		TypeInfo<float >::parseFromBinaryStream(&saberResist, stream);
		return true;

	case 0x49826072: //DnaComponent.sourceLevel
		TypeInfo<int >::parseFromBinaryStream(&sourceLevel, stream);
		return true;

	case 0x5926cd20: //DnaComponent.specialResists
		TypeInfo<int >::parseFromBinaryStream(&specialResists, stream);
		return true;

	}

	return false;
}

void DnaComponentImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DnaComponentImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DnaComponentImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ComponentImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x537315ca; //DnaComponent.cleverness
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&cleverness, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xf4af7fae; //DnaComponent.endurance
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&endurance, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xf43f9d83; //DnaComponent.fierceness
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&fierceness, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xefc2f678; //DnaComponent.power
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&power, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xa2aa299c; //DnaComponent.intelligence
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&intelligence, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xbf786897; //DnaComponent.courage
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&courage, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x65db69d9; //DnaComponent.dependency
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&dependency, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x3de40934; //DnaComponent.dexterity
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&dexterity, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x8fefaa2b; //DnaComponent.fortitude
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&fortitude, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x4583898d; //DnaComponent.hardiness
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&hardiness, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7e2ce408; //DnaComponent.source
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&source, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x951debae; //DnaComponent.special1
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&special1, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x985ecd77; //DnaComponent.special2
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&special2, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x2add1d2; //DnaComponent.ranged
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&ranged, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xe6a04868; //DnaComponent.quality
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&quality, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x82a47260; //DnaComponent.armorRating
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&armorRating, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x73708b36; //DnaComponent.kinResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&kinResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x9817b856; //DnaComponent.energyResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&energyResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x3510d3f8; //DnaComponent.blastResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&blastResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xe82e7169; //DnaComponent.coldResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&coldResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x17442b7a; //DnaComponent.heatResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&heatResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x938671cb; //DnaComponent.elecResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&elecResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x972a1231; //DnaComponent.acidResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&acidResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x8c896caf; //DnaComponent.stunResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&stunResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x37c50636; //DnaComponent.saberResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&saberResist, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x49826072; //DnaComponent.sourceLevel
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&sourceLevel, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x5926cd20; //DnaComponent.specialResists
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&specialResists, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void DnaComponentImplementation::writeJSON(nlohmann::json& j) {
	ComponentImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["cleverness"] = cleverness;

	thisObject["endurance"] = endurance;

	thisObject["fierceness"] = fierceness;

	thisObject["power"] = power;

	thisObject["intelligence"] = intelligence;

	thisObject["courage"] = courage;

	thisObject["dependency"] = dependency;

	thisObject["dexterity"] = dexterity;

	thisObject["fortitude"] = fortitude;

	thisObject["hardiness"] = hardiness;

	thisObject["source"] = source;

	thisObject["special1"] = special1;

	thisObject["special2"] = special2;

	thisObject["ranged"] = ranged;

	thisObject["quality"] = quality;

	thisObject["armorRating"] = armorRating;

	thisObject["kinResist"] = kinResist;

	thisObject["energyResist"] = energyResist;

	thisObject["blastResist"] = blastResist;

	thisObject["coldResist"] = coldResist;

	thisObject["heatResist"] = heatResist;

	thisObject["elecResist"] = elecResist;

	thisObject["acidResist"] = acidResist;

	thisObject["stunResist"] = stunResist;

	thisObject["saberResist"] = saberResist;

	thisObject["sourceLevel"] = sourceLevel;

	thisObject["specialResists"] = specialResists;

	j["DnaComponent"] = thisObject;
}

DnaComponentImplementation::DnaComponentImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		Logger.setLoggingName("DnaComponent");
	Logger::setLoggingName("DnaComponent");
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		cleverness = 0;
	cleverness = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		endurance = 0;
	endurance = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		fierceness = 0;
	fierceness = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		power = 0;
	power = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		intelligence = 0;
	intelligence = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		courage = 0;
	courage = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		dependency = 0;
	dependency = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		dexterity = 0;
	dexterity = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		fortitude = 0;
	fortitude = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		hardiness = 0;
	hardiness = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		source = "unknown";
	source = "unknown";
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		special1 = "none";
	special1 = "none";
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		special2 = "none";
	special2 = "none";
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		ranged = false;
	ranged = false;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		quality = 7;
	quality = 7;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		armorRating = 0;
	armorRating = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		kinResist = 0;
	kinResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		energyResist = 0;
	energyResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		blastResist = 0;
	blastResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		coldResist = 0;
	coldResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		heatResist = 0;
	heatResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		elecResist = 0;
	elecResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		acidResist = 0;
	acidResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		stunResist = 0;
	stunResist = 0;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		saberResist = -1;
	saberResist = -1;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		sourceLevel = 1;
	sourceLevel = 1;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		specialResists = 0;
	specialResists = 0;
}

void DnaComponentImplementation::setStats(int cle, int end, int fie, int pow, int ite, int cou, int dep, int dex, int frt, int har) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		cleverness = cle;
	cleverness = cle;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		endurance = end;
	endurance = end;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		fierceness = fie;
	fierceness = fie;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		power = pow;
	power = pow;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		intelligence = ite;
	intelligence = ite;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		courage = cou;
	courage = cou;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		dependency = dep;
	dependency = dep;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		fortitude = frt;
	fortitude = frt;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		hardiness = har;
	hardiness = har;
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		dexterity = dex;
	dexterity = dex;
}

void DnaComponentImplementation::setCleverness(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		cleverness = value;
	cleverness = value;
}

int DnaComponentImplementation::getCleverness() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return cleverness;
	return cleverness;
}

void DnaComponentImplementation::setLevel(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		sourceLevel = value;
	sourceLevel = value;
}

int DnaComponentImplementation::getLevel() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return sourceLevel;
	return sourceLevel;
}

void DnaComponentImplementation::setEndurance(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		endurance = value;
	endurance = value;
}

int DnaComponentImplementation::getEndurance() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return endurance;
	return endurance;
}

void DnaComponentImplementation::setFierceness(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		fierceness = value;
	fierceness = value;
}

int DnaComponentImplementation::getFierceness() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return fierceness;
	return fierceness;
}

void DnaComponentImplementation::setPower(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		power = value;
	power = value;
}

int DnaComponentImplementation::getPower() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return power;
	return power;
}

void DnaComponentImplementation::setIntellect(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		intelligence = value;
	intelligence = value;
}

int DnaComponentImplementation::getIntellect() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return intelligence;
	return intelligence;
}

void DnaComponentImplementation::setCourage(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		courage = value;
	courage = value;
}

int DnaComponentImplementation::getCourage() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return courage;
	return courage;
}

void DnaComponentImplementation::setDependency(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		dependency = value;
	dependency = value;
}

int DnaComponentImplementation::getDependency() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return dependency;
	return dependency;
}

void DnaComponentImplementation::setDexterity(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		dexterity = value;
	dexterity = value;
}

int DnaComponentImplementation::getDexterity() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return dexterity;
	return dexterity;
}

void DnaComponentImplementation::setFortitude(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		fortitude = value;
	fortitude = value;
}

int DnaComponentImplementation::getForititude() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return fortitude;
	return fortitude;
}

void DnaComponentImplementation::setHardiness(int value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		hardiness = value;
	hardiness = value;
}

int DnaComponentImplementation::getHardiness() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return hardiness;
	return hardiness;
}

void DnaComponentImplementation::setEnergy(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		energyResist = value;
	energyResist = value;
}

float DnaComponentImplementation::getEnergy() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return energyResist;
	return energyResist;
}

void DnaComponentImplementation::setBlast(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		blastResist = value;
	blastResist = value;
}

float DnaComponentImplementation::getBlast() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return blastResist;
	return blastResist;
}

void DnaComponentImplementation::setCold(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		coldResist = value;
	coldResist = value;
}

float DnaComponentImplementation::getCold() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return coldResist;
	return coldResist;
}

void DnaComponentImplementation::setHeat(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		heatResist = value;
	heatResist = value;
}

float DnaComponentImplementation::getHeat() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return heatResist;
	return heatResist;
}

void DnaComponentImplementation::setElectric(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		elecResist = value;
	elecResist = value;
}

float DnaComponentImplementation::getElectric() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return elecResist;
	return elecResist;
}

void DnaComponentImplementation::setAcid(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		acidResist = value;
	acidResist = value;
}

float DnaComponentImplementation::getAcid() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return acidResist;
	return acidResist;
}

void DnaComponentImplementation::setStun(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		stunResist = value;
	stunResist = value;
}

float DnaComponentImplementation::getStun() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return stunResist;
	return stunResist;
}

void DnaComponentImplementation::setSaber(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		saberResist = value;
	saberResist = value;
}

float DnaComponentImplementation::getSaber() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return saberResist;
	return saberResist;
}

void DnaComponentImplementation::setArmorRating(int rating) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		armorRating = rating;
	armorRating = rating;
}

void DnaComponentImplementation::setKinetic(float value) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		kinResist = value;
	kinResist = value;
}

float DnaComponentImplementation::getKinetic() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return kinResist;
	return kinResist;
}

void DnaComponentImplementation::setSource(const String& src) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		source = src;
	source = src;
}

void DnaComponentImplementation::setSpecialAttackOne(const String& atk) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		special1 = atk;
	special1 = atk;
}

String DnaComponentImplementation::getSpecialAttackOne() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return special1;
	return special1;
}

void DnaComponentImplementation::setSpecialAttackTwo(const String& atk) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		special2 = atk;
	special2 = atk;
}

String DnaComponentImplementation::getSpecialAttackTwo() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return special2;
	return special2;
}

void DnaComponentImplementation::setRanged(bool b) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		ranged = b;
	ranged = b;
}

bool DnaComponentImplementation::isRanged() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return ranged;
	return ranged;
}

void DnaComponentImplementation::setQuality(int qual) {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		quality = qual;
	quality = qual;
}

unsigned int DnaComponentImplementation::getQuality() {
	// server/zone/objects/tangible/component/dna/DnaComponent.idl():  		return quality;
	return quality;
}

/*
 *	DnaComponentAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


DnaComponentAdapter::DnaComponentAdapter(DnaComponent* obj) : ComponentAdapter(obj) {
}

void DnaComponentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_SETSTATS__INT_INT_INT_INT_INT_INT_INT_INT_INT_INT_:
		{
			int cle = inv->getSignedIntParameter();
			int end = inv->getSignedIntParameter();
			int fie = inv->getSignedIntParameter();
			int pow = inv->getSignedIntParameter();
			int ite = inv->getSignedIntParameter();
			int cou = inv->getSignedIntParameter();
			int dep = inv->getSignedIntParameter();
			int dex = inv->getSignedIntParameter();
			int frt = inv->getSignedIntParameter();
			int har = inv->getSignedIntParameter();
			
			setStats(cle, end, fie, pow, ite, cou, dep, dex, frt, har);
			
		}
		break;
	case RPC_SETSPECIALRESIST__INT_:
		{
			int type = inv->getSignedIntParameter();
			
			setSpecialResist(type);
			
		}
		break;
	case RPC_ISSPECIALRESIST__INT_:
		{
			int type = inv->getSignedIntParameter();
			
			bool _m_res = isSpecialResist(type);
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETCLEVERNESS__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setCleverness(value);
			
		}
		break;
	case RPC_GETCLEVERNESS__:
		{
			
			int _m_res = getCleverness();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETLEVEL__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setLevel(value);
			
		}
		break;
	case RPC_GETLEVEL__:
		{
			
			int _m_res = getLevel();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETENDURANCE__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setEndurance(value);
			
		}
		break;
	case RPC_GETENDURANCE__:
		{
			
			int _m_res = getEndurance();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETFIERCENESS__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setFierceness(value);
			
		}
		break;
	case RPC_GETFIERCENESS__:
		{
			
			int _m_res = getFierceness();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETPOWER__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setPower(value);
			
		}
		break;
	case RPC_GETPOWER__:
		{
			
			int _m_res = getPower();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETINTELLECT__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setIntellect(value);
			
		}
		break;
	case RPC_GETINTELLECT__:
		{
			
			int _m_res = getIntellect();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETCOURAGE__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setCourage(value);
			
		}
		break;
	case RPC_GETCOURAGE__:
		{
			
			int _m_res = getCourage();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETDEPENDENCY__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setDependency(value);
			
		}
		break;
	case RPC_GETDEPENDENCY__:
		{
			
			int _m_res = getDependency();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETDEXTERITY__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setDexterity(value);
			
		}
		break;
	case RPC_GETDEXTERITY__:
		{
			
			int _m_res = getDexterity();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETFORTITUDE__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setFortitude(value);
			
		}
		break;
	case RPC_GETFORITITUDE__:
		{
			
			int _m_res = getForititude();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETHARDINESS__INT_:
		{
			int value = inv->getSignedIntParameter();
			
			setHardiness(value);
			
		}
		break;
	case RPC_GETHARDINESS__:
		{
			
			int _m_res = getHardiness();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETENERGY__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setEnergy(value);
			
		}
		break;
	case RPC_GETENERGY__:
		{
			
			float _m_res = getEnergy();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETBLAST__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setBlast(value);
			
		}
		break;
	case RPC_GETBLAST__:
		{
			
			float _m_res = getBlast();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETCOLD__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setCold(value);
			
		}
		break;
	case RPC_GETCOLD__:
		{
			
			float _m_res = getCold();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETHEAT__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setHeat(value);
			
		}
		break;
	case RPC_GETHEAT__:
		{
			
			float _m_res = getHeat();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETELECTRIC__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setElectric(value);
			
		}
		break;
	case RPC_GETELECTRIC__:
		{
			
			float _m_res = getElectric();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETACID__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setAcid(value);
			
		}
		break;
	case RPC_GETACID__:
		{
			
			float _m_res = getAcid();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETSTUN__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setStun(value);
			
		}
		break;
	case RPC_GETSTUN__:
		{
			
			float _m_res = getStun();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETSABER__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setSaber(value);
			
		}
		break;
	case RPC_GETSABER__:
		{
			
			float _m_res = getSaber();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETARMORRATING__INT_:
		{
			int rating = inv->getSignedIntParameter();
			
			setArmorRating(rating);
			
		}
		break;
	case RPC_SETKINETIC__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setKinetic(value);
			
		}
		break;
	case RPC_GETKINETIC__:
		{
			
			float _m_res = getKinetic();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETSOURCE__STRING_:
		{
			 String src; inv->getAsciiParameter(src);
			
			setSource(src);
			
		}
		break;
	case RPC_SETSPECIALATTACKONE__STRING_:
		{
			 String atk; inv->getAsciiParameter(atk);
			
			setSpecialAttackOne(atk);
			
		}
		break;
	case RPC_GETSPECIALATTACKONE__:
		{
			
			String _m_res = getSpecialAttackOne();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_SETSPECIALATTACKTWO__STRING_:
		{
			 String atk; inv->getAsciiParameter(atk);
			
			setSpecialAttackTwo(atk);
			
		}
		break;
	case RPC_GETSPECIALATTACKTWO__:
		{
			
			String _m_res = getSpecialAttackTwo();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_SETRANGED__BOOL_:
		{
			bool b = inv->getBooleanParameter();
			
			setRanged(b);
			
		}
		break;
	case RPC_ISRANGED__:
		{
			
			bool _m_res = isRanged();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETQUALITY__INT_:
		{
			int qual = inv->getSignedIntParameter();
			
			setQuality(qual);
			
		}
		break;
	case RPC_GETQUALITY__:
		{
			
			unsigned int _m_res = getQuality();
			resp->insertInt(_m_res);
		}
		break;
	case RPC_INITIALIZETRANSIENTMEMBERS__:
		{
			
			initializeTransientMembers();
			
		}
		break;
	case RPC_CONVERTSPECIALATTACK__STRING_:
		{
			String attackName; inv->getAsciiParameter(attackName);
			
			String _m_res = convertSpecialAttack(attackName);
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_RESISTVALUE__FLOAT_:
		{
			float input = inv->getFloatParameter();
			
			String _m_res = resistValue(input);
			resp->insertAscii(_m_res);
		}
		break;
	default:
		ComponentAdapter::invokeMethod(methid, inv);
	}
}

void DnaComponentAdapter::setStats(int cle, int end, int fie, int pow, int ite, int cou, int dep, int dex, int frt, int har) {
	(static_cast<DnaComponent*>(stub))->setStats(cle, end, fie, pow, ite, cou, dep, dex, frt, har);
}

void DnaComponentAdapter::setSpecialResist(int type) {
	(static_cast<DnaComponent*>(stub))->setSpecialResist(type);
}

bool DnaComponentAdapter::isSpecialResist(int type) {
	return (static_cast<DnaComponent*>(stub))->isSpecialResist(type);
}

void DnaComponentAdapter::setCleverness(int value) {
	(static_cast<DnaComponent*>(stub))->setCleverness(value);
}

int DnaComponentAdapter::getCleverness() {
	return (static_cast<DnaComponent*>(stub))->getCleverness();
}

void DnaComponentAdapter::setLevel(int value) {
	(static_cast<DnaComponent*>(stub))->setLevel(value);
}

int DnaComponentAdapter::getLevel() {
	return (static_cast<DnaComponent*>(stub))->getLevel();
}

void DnaComponentAdapter::setEndurance(int value) {
	(static_cast<DnaComponent*>(stub))->setEndurance(value);
}

int DnaComponentAdapter::getEndurance() {
	return (static_cast<DnaComponent*>(stub))->getEndurance();
}

void DnaComponentAdapter::setFierceness(int value) {
	(static_cast<DnaComponent*>(stub))->setFierceness(value);
}

int DnaComponentAdapter::getFierceness() {
	return (static_cast<DnaComponent*>(stub))->getFierceness();
}

void DnaComponentAdapter::setPower(int value) {
	(static_cast<DnaComponent*>(stub))->setPower(value);
}

int DnaComponentAdapter::getPower() {
	return (static_cast<DnaComponent*>(stub))->getPower();
}

void DnaComponentAdapter::setIntellect(int value) {
	(static_cast<DnaComponent*>(stub))->setIntellect(value);
}

int DnaComponentAdapter::getIntellect() {
	return (static_cast<DnaComponent*>(stub))->getIntellect();
}

void DnaComponentAdapter::setCourage(int value) {
	(static_cast<DnaComponent*>(stub))->setCourage(value);
}

int DnaComponentAdapter::getCourage() {
	return (static_cast<DnaComponent*>(stub))->getCourage();
}

void DnaComponentAdapter::setDependency(int value) {
	(static_cast<DnaComponent*>(stub))->setDependency(value);
}

int DnaComponentAdapter::getDependency() {
	return (static_cast<DnaComponent*>(stub))->getDependency();
}

void DnaComponentAdapter::setDexterity(int value) {
	(static_cast<DnaComponent*>(stub))->setDexterity(value);
}

int DnaComponentAdapter::getDexterity() {
	return (static_cast<DnaComponent*>(stub))->getDexterity();
}

void DnaComponentAdapter::setFortitude(int value) {
	(static_cast<DnaComponent*>(stub))->setFortitude(value);
}

int DnaComponentAdapter::getForititude() {
	return (static_cast<DnaComponent*>(stub))->getForititude();
}

void DnaComponentAdapter::setHardiness(int value) {
	(static_cast<DnaComponent*>(stub))->setHardiness(value);
}

int DnaComponentAdapter::getHardiness() {
	return (static_cast<DnaComponent*>(stub))->getHardiness();
}

void DnaComponentAdapter::setEnergy(float value) {
	(static_cast<DnaComponent*>(stub))->setEnergy(value);
}

float DnaComponentAdapter::getEnergy() {
	return (static_cast<DnaComponent*>(stub))->getEnergy();
}

void DnaComponentAdapter::setBlast(float value) {
	(static_cast<DnaComponent*>(stub))->setBlast(value);
}

float DnaComponentAdapter::getBlast() {
	return (static_cast<DnaComponent*>(stub))->getBlast();
}

void DnaComponentAdapter::setCold(float value) {
	(static_cast<DnaComponent*>(stub))->setCold(value);
}

float DnaComponentAdapter::getCold() {
	return (static_cast<DnaComponent*>(stub))->getCold();
}

void DnaComponentAdapter::setHeat(float value) {
	(static_cast<DnaComponent*>(stub))->setHeat(value);
}

float DnaComponentAdapter::getHeat() {
	return (static_cast<DnaComponent*>(stub))->getHeat();
}

void DnaComponentAdapter::setElectric(float value) {
	(static_cast<DnaComponent*>(stub))->setElectric(value);
}

float DnaComponentAdapter::getElectric() {
	return (static_cast<DnaComponent*>(stub))->getElectric();
}

void DnaComponentAdapter::setAcid(float value) {
	(static_cast<DnaComponent*>(stub))->setAcid(value);
}

float DnaComponentAdapter::getAcid() {
	return (static_cast<DnaComponent*>(stub))->getAcid();
}

void DnaComponentAdapter::setStun(float value) {
	(static_cast<DnaComponent*>(stub))->setStun(value);
}

float DnaComponentAdapter::getStun() {
	return (static_cast<DnaComponent*>(stub))->getStun();
}

void DnaComponentAdapter::setSaber(float value) {
	(static_cast<DnaComponent*>(stub))->setSaber(value);
}

float DnaComponentAdapter::getSaber() {
	return (static_cast<DnaComponent*>(stub))->getSaber();
}

void DnaComponentAdapter::setArmorRating(int rating) {
	(static_cast<DnaComponent*>(stub))->setArmorRating(rating);
}

void DnaComponentAdapter::setKinetic(float value) {
	(static_cast<DnaComponent*>(stub))->setKinetic(value);
}

float DnaComponentAdapter::getKinetic() {
	return (static_cast<DnaComponent*>(stub))->getKinetic();
}

void DnaComponentAdapter::setSource(const String& src) {
	(static_cast<DnaComponent*>(stub))->setSource(src);
}

void DnaComponentAdapter::setSpecialAttackOne(const String& atk) {
	(static_cast<DnaComponent*>(stub))->setSpecialAttackOne(atk);
}

String DnaComponentAdapter::getSpecialAttackOne() {
	return (static_cast<DnaComponent*>(stub))->getSpecialAttackOne();
}

void DnaComponentAdapter::setSpecialAttackTwo(const String& atk) {
	(static_cast<DnaComponent*>(stub))->setSpecialAttackTwo(atk);
}

String DnaComponentAdapter::getSpecialAttackTwo() {
	return (static_cast<DnaComponent*>(stub))->getSpecialAttackTwo();
}

void DnaComponentAdapter::setRanged(bool b) {
	(static_cast<DnaComponent*>(stub))->setRanged(b);
}

bool DnaComponentAdapter::isRanged() {
	return (static_cast<DnaComponent*>(stub))->isRanged();
}

void DnaComponentAdapter::setQuality(int qual) {
	(static_cast<DnaComponent*>(stub))->setQuality(qual);
}

unsigned int DnaComponentAdapter::getQuality() {
	return (static_cast<DnaComponent*>(stub))->getQuality();
}

void DnaComponentAdapter::initializeTransientMembers() {
	(static_cast<DnaComponent*>(stub))->initializeTransientMembers();
}

String DnaComponentAdapter::convertSpecialAttack(String& attackName) {
	return (static_cast<DnaComponent*>(stub))->convertSpecialAttack(attackName);
}

String DnaComponentAdapter::resistValue(float input) {
	return (static_cast<DnaComponent*>(stub))->resistValue(input);
}

/*
 *	DnaComponentHelper
 */

DnaComponentHelper* DnaComponentHelper::staticInitializer = DnaComponentHelper::instance();

DnaComponentHelper::DnaComponentHelper() {
	className = "DnaComponent";

	Core::getObjectBroker()->registerClass(className, this);
}

void DnaComponentHelper::finalizeHelper() {
	DnaComponentHelper::finalize();
}

DistributedObject* DnaComponentHelper::instantiateObject() {
	return new DnaComponent(DummyConstructorParameter::instance());
}

DistributedObjectServant* DnaComponentHelper::instantiateServant() {
	return new DnaComponentImplementation();
}

DistributedObjectPOD* DnaComponentHelper::instantiatePOD() {
	return new DnaComponentPOD();
}

DistributedObjectAdapter* DnaComponentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new DnaComponentAdapter(static_cast<DnaComponent*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	DnaComponentPOD
 */

DnaComponentPOD::~DnaComponentPOD() {
	finalize();
}

DnaComponentPOD::DnaComponentPOD(void) {
	_className = "DnaComponent";
}


void DnaComponentPOD::writeJSON(nlohmann::json& j) {
	ComponentPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (cleverness)
		thisObject["cleverness"] = cleverness.value();

	if (endurance)
		thisObject["endurance"] = endurance.value();

	if (fierceness)
		thisObject["fierceness"] = fierceness.value();

	if (power)
		thisObject["power"] = power.value();

	if (intelligence)
		thisObject["intelligence"] = intelligence.value();

	if (courage)
		thisObject["courage"] = courage.value();

	if (dependency)
		thisObject["dependency"] = dependency.value();

	if (dexterity)
		thisObject["dexterity"] = dexterity.value();

	if (fortitude)
		thisObject["fortitude"] = fortitude.value();

	if (hardiness)
		thisObject["hardiness"] = hardiness.value();

	if (source)
		thisObject["source"] = source.value();

	if (special1)
		thisObject["special1"] = special1.value();

	if (special2)
		thisObject["special2"] = special2.value();

	if (ranged)
		thisObject["ranged"] = ranged.value();

	if (quality)
		thisObject["quality"] = quality.value();

	if (armorRating)
		thisObject["armorRating"] = armorRating.value();

	if (kinResist)
		thisObject["kinResist"] = kinResist.value();

	if (energyResist)
		thisObject["energyResist"] = energyResist.value();

	if (blastResist)
		thisObject["blastResist"] = blastResist.value();

	if (coldResist)
		thisObject["coldResist"] = coldResist.value();

	if (heatResist)
		thisObject["heatResist"] = heatResist.value();

	if (elecResist)
		thisObject["elecResist"] = elecResist.value();

	if (acidResist)
		thisObject["acidResist"] = acidResist.value();

	if (stunResist)
		thisObject["stunResist"] = stunResist.value();

	if (saberResist)
		thisObject["saberResist"] = saberResist.value();

	if (sourceLevel)
		thisObject["sourceLevel"] = sourceLevel.value();

	if (specialResists)
		thisObject["specialResists"] = specialResists.value();

	j["DnaComponent"] = thisObject;
}


void DnaComponentPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DnaComponentPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DnaComponentPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ComponentPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (cleverness) {
	_nameHashCode = 0x537315ca; //DnaComponent.cleverness
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&cleverness.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (endurance) {
	_nameHashCode = 0xf4af7fae; //DnaComponent.endurance
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&endurance.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (fierceness) {
	_nameHashCode = 0xf43f9d83; //DnaComponent.fierceness
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&fierceness.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (power) {
	_nameHashCode = 0xefc2f678; //DnaComponent.power
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&power.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (intelligence) {
	_nameHashCode = 0xa2aa299c; //DnaComponent.intelligence
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&intelligence.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (courage) {
	_nameHashCode = 0xbf786897; //DnaComponent.courage
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&courage.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (dependency) {
	_nameHashCode = 0x65db69d9; //DnaComponent.dependency
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&dependency.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (dexterity) {
	_nameHashCode = 0x3de40934; //DnaComponent.dexterity
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&dexterity.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (fortitude) {
	_nameHashCode = 0x8fefaa2b; //DnaComponent.fortitude
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&fortitude.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (hardiness) {
	_nameHashCode = 0x4583898d; //DnaComponent.hardiness
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&hardiness.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (source) {
	_nameHashCode = 0x7e2ce408; //DnaComponent.source
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&source.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (special1) {
	_nameHashCode = 0x951debae; //DnaComponent.special1
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&special1.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (special2) {
	_nameHashCode = 0x985ecd77; //DnaComponent.special2
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&special2.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (ranged) {
	_nameHashCode = 0x2add1d2; //DnaComponent.ranged
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&ranged.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (quality) {
	_nameHashCode = 0xe6a04868; //DnaComponent.quality
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&quality.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (armorRating) {
	_nameHashCode = 0x82a47260; //DnaComponent.armorRating
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&armorRating.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (kinResist) {
	_nameHashCode = 0x73708b36; //DnaComponent.kinResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&kinResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (energyResist) {
	_nameHashCode = 0x9817b856; //DnaComponent.energyResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&energyResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (blastResist) {
	_nameHashCode = 0x3510d3f8; //DnaComponent.blastResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&blastResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (coldResist) {
	_nameHashCode = 0xe82e7169; //DnaComponent.coldResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&coldResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (heatResist) {
	_nameHashCode = 0x17442b7a; //DnaComponent.heatResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&heatResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (elecResist) {
	_nameHashCode = 0x938671cb; //DnaComponent.elecResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&elecResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (acidResist) {
	_nameHashCode = 0x972a1231; //DnaComponent.acidResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&acidResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (stunResist) {
	_nameHashCode = 0x8c896caf; //DnaComponent.stunResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&stunResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (saberResist) {
	_nameHashCode = 0x37c50636; //DnaComponent.saberResist
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&saberResist.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (sourceLevel) {
	_nameHashCode = 0x49826072; //DnaComponent.sourceLevel
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&sourceLevel.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (specialResists) {
	_nameHashCode = 0x5926cd20; //DnaComponent.specialResists
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&specialResists.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool DnaComponentPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ComponentPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x537315ca: //DnaComponent.cleverness
		{
			int _mncleverness;
			TypeInfo<int >::parseFromBinaryStream(&_mncleverness, stream);
			cleverness = std::move(_mncleverness);
		}
		return true;

	case 0xf4af7fae: //DnaComponent.endurance
		{
			int _mnendurance;
			TypeInfo<int >::parseFromBinaryStream(&_mnendurance, stream);
			endurance = std::move(_mnendurance);
		}
		return true;

	case 0xf43f9d83: //DnaComponent.fierceness
		{
			int _mnfierceness;
			TypeInfo<int >::parseFromBinaryStream(&_mnfierceness, stream);
			fierceness = std::move(_mnfierceness);
		}
		return true;

	case 0xefc2f678: //DnaComponent.power
		{
			int _mnpower;
			TypeInfo<int >::parseFromBinaryStream(&_mnpower, stream);
			power = std::move(_mnpower);
		}
		return true;

	case 0xa2aa299c: //DnaComponent.intelligence
		{
			int _mnintelligence;
			TypeInfo<int >::parseFromBinaryStream(&_mnintelligence, stream);
			intelligence = std::move(_mnintelligence);
		}
		return true;

	case 0xbf786897: //DnaComponent.courage
		{
			int _mncourage;
			TypeInfo<int >::parseFromBinaryStream(&_mncourage, stream);
			courage = std::move(_mncourage);
		}
		return true;

	case 0x65db69d9: //DnaComponent.dependency
		{
			int _mndependency;
			TypeInfo<int >::parseFromBinaryStream(&_mndependency, stream);
			dependency = std::move(_mndependency);
		}
		return true;

	case 0x3de40934: //DnaComponent.dexterity
		{
			int _mndexterity;
			TypeInfo<int >::parseFromBinaryStream(&_mndexterity, stream);
			dexterity = std::move(_mndexterity);
		}
		return true;

	case 0x8fefaa2b: //DnaComponent.fortitude
		{
			int _mnfortitude;
			TypeInfo<int >::parseFromBinaryStream(&_mnfortitude, stream);
			fortitude = std::move(_mnfortitude);
		}
		return true;

	case 0x4583898d: //DnaComponent.hardiness
		{
			int _mnhardiness;
			TypeInfo<int >::parseFromBinaryStream(&_mnhardiness, stream);
			hardiness = std::move(_mnhardiness);
		}
		return true;

	case 0x7e2ce408: //DnaComponent.source
		{
			String _mnsource;
			TypeInfo<String >::parseFromBinaryStream(&_mnsource, stream);
			source = std::move(_mnsource);
		}
		return true;

	case 0x951debae: //DnaComponent.special1
		{
			String _mnspecial1;
			TypeInfo<String >::parseFromBinaryStream(&_mnspecial1, stream);
			special1 = std::move(_mnspecial1);
		}
		return true;

	case 0x985ecd77: //DnaComponent.special2
		{
			String _mnspecial2;
			TypeInfo<String >::parseFromBinaryStream(&_mnspecial2, stream);
			special2 = std::move(_mnspecial2);
		}
		return true;

	case 0x2add1d2: //DnaComponent.ranged
		{
			bool _mnranged;
			TypeInfo<bool >::parseFromBinaryStream(&_mnranged, stream);
			ranged = std::move(_mnranged);
		}
		return true;

	case 0xe6a04868: //DnaComponent.quality
		{
			int _mnquality;
			TypeInfo<int >::parseFromBinaryStream(&_mnquality, stream);
			quality = std::move(_mnquality);
		}
		return true;

	case 0x82a47260: //DnaComponent.armorRating
		{
			int _mnarmorRating;
			TypeInfo<int >::parseFromBinaryStream(&_mnarmorRating, stream);
			armorRating = std::move(_mnarmorRating);
		}
		return true;

	case 0x73708b36: //DnaComponent.kinResist
		{
			float _mnkinResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnkinResist, stream);
			kinResist = std::move(_mnkinResist);
		}
		return true;

	case 0x9817b856: //DnaComponent.energyResist
		{
			float _mnenergyResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnenergyResist, stream);
			energyResist = std::move(_mnenergyResist);
		}
		return true;

	case 0x3510d3f8: //DnaComponent.blastResist
		{
			float _mnblastResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnblastResist, stream);
			blastResist = std::move(_mnblastResist);
		}
		return true;

	case 0xe82e7169: //DnaComponent.coldResist
		{
			float _mncoldResist;
			TypeInfo<float >::parseFromBinaryStream(&_mncoldResist, stream);
			coldResist = std::move(_mncoldResist);
		}
		return true;

	case 0x17442b7a: //DnaComponent.heatResist
		{
			float _mnheatResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnheatResist, stream);
			heatResist = std::move(_mnheatResist);
		}
		return true;

	case 0x938671cb: //DnaComponent.elecResist
		{
			float _mnelecResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnelecResist, stream);
			elecResist = std::move(_mnelecResist);
		}
		return true;

	case 0x972a1231: //DnaComponent.acidResist
		{
			float _mnacidResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnacidResist, stream);
			acidResist = std::move(_mnacidResist);
		}
		return true;

	case 0x8c896caf: //DnaComponent.stunResist
		{
			float _mnstunResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnstunResist, stream);
			stunResist = std::move(_mnstunResist);
		}
		return true;

	case 0x37c50636: //DnaComponent.saberResist
		{
			float _mnsaberResist;
			TypeInfo<float >::parseFromBinaryStream(&_mnsaberResist, stream);
			saberResist = std::move(_mnsaberResist);
		}
		return true;

	case 0x49826072: //DnaComponent.sourceLevel
		{
			int _mnsourceLevel;
			TypeInfo<int >::parseFromBinaryStream(&_mnsourceLevel, stream);
			sourceLevel = std::move(_mnsourceLevel);
		}
		return true;

	case 0x5926cd20: //DnaComponent.specialResists
		{
			int _mnspecialResists;
			TypeInfo<int >::parseFromBinaryStream(&_mnspecialResists, stream);
			specialResists = std::move(_mnspecialResists);
		}
		return true;

	}

	return false;
}

void DnaComponentPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DnaComponentPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void DnaComponentPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ComponentPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&cleverness.value(), stream);

	TypeInfo<int >::toBinaryStream(&endurance.value(), stream);

	TypeInfo<int >::toBinaryStream(&fierceness.value(), stream);

	TypeInfo<int >::toBinaryStream(&power.value(), stream);

	TypeInfo<int >::toBinaryStream(&intelligence.value(), stream);

	TypeInfo<int >::toBinaryStream(&courage.value(), stream);

	TypeInfo<int >::toBinaryStream(&dependency.value(), stream);

	TypeInfo<int >::toBinaryStream(&dexterity.value(), stream);

	TypeInfo<int >::toBinaryStream(&fortitude.value(), stream);

	TypeInfo<int >::toBinaryStream(&hardiness.value(), stream);

	TypeInfo<String >::toBinaryStream(&source.value(), stream);

	TypeInfo<String >::toBinaryStream(&special1.value(), stream);

	TypeInfo<String >::toBinaryStream(&special2.value(), stream);

	TypeInfo<bool >::toBinaryStream(&ranged.value(), stream);

	TypeInfo<int >::toBinaryStream(&quality.value(), stream);

	TypeInfo<int >::toBinaryStream(&armorRating.value(), stream);

	TypeInfo<float >::toBinaryStream(&kinResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&energyResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&blastResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&coldResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&heatResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&elecResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&acidResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&stunResist.value(), stream);

	TypeInfo<float >::toBinaryStream(&saberResist.value(), stream);

	TypeInfo<int >::toBinaryStream(&sourceLevel.value(), stream);

	TypeInfo<int >::toBinaryStream(&specialResists.value(), stream);


}

