/*
                Copyright <SWGEmu>
        See file COPYING for copying conditions. */

include engine.core.ManagedObject;

import engine.log.Logger;
import engine.core.ManagedReference;
import system.lang.ref.Reference;
import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.creature.CreatureObject;
include templates.params.ObserverEventType;

class CloakEventObserver extends Observer implements Logger {
    @weakReference
    protected CreatureObject player;

    public CloakEventObserver(CreatureObject pl) {
        player = pl;

        Logger.setLoggingName("CloakEventObserver");
        Logger.setLogging(true);
    }

    @dirty
    public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);

    @weakReference
    @read
    public CreatureObject getPlayer() {
        return player;
    }
}
