/*
 *	autogen/server/zone/objects/player/sessions/MigrateStatsSession.cpp generated by engine3 IDL compiler 0.70
 */

#include "MigrateStatsSession.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	MigrateStatsSessionStub
 */

enum {RPC_INITIALIZESESSION__ = 1654755279,RPC_CANCELSESSION__,RPC_CLEARSESSION__,RPC_GETATTRIBUTETOMODIFYCOUNT__,RPC_SETATTRIBUTETOMODIFY__INT_INT_,RPC_GETATTRIBTUETOMODIFY__INT_,RPC_MIGRATESTATS__};

MigrateStatsSession::MigrateStatsSession(CreatureObject* parent) : Facade(DummyConstructorParameter::instance()) {
	MigrateStatsSessionImplementation* _implementation = new MigrateStatsSessionImplementation(parent);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("MigrateStatsSession");
}

MigrateStatsSession::MigrateStatsSession(DummyConstructorParameter* param) : Facade(param) {
	_setClassName("MigrateStatsSession");
}

MigrateStatsSession::~MigrateStatsSession() {
}



int MigrateStatsSession::initializeSession() {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZESESSION__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->initializeSession();
	}
}

int MigrateStatsSession::cancelSession() {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CANCELSESSION__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->cancelSession();
	}
}

int MigrateStatsSession::clearSession() {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CLEARSESSION__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->clearSession();
	}
}

int MigrateStatsSession::getAttributeToModifyCount() {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETATTRIBUTETOMODIFYCOUNT__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getAttributeToModifyCount();
	}
}

void MigrateStatsSession::setAttributeToModify(int attribute, int value) {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETATTRIBUTETOMODIFY__INT_INT_);
		method.addSignedIntParameter(attribute);
		method.addSignedIntParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setAttributeToModify(attribute, value);
	}
}

int MigrateStatsSession::getAttribtueToModify(int attribute) {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETATTRIBTUETOMODIFY__INT_);
		method.addSignedIntParameter(attribute);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getAttribtueToModify(attribute);
	}
}

void MigrateStatsSession::migrateStats() {
	MigrateStatsSessionImplementation* _implementation = static_cast<MigrateStatsSessionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_MIGRATESTATS__);

		method.executeWithVoidReturn();
	} else {
		_implementation->migrateStats();
	}
}

DistributedObjectServant* MigrateStatsSession::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* MigrateStatsSession::_getImplementationForRead() const {
	return _impl;
}

void MigrateStatsSession::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	MigrateStatsSessionImplementation
 */

MigrateStatsSessionImplementation::MigrateStatsSessionImplementation(DummyConstructorParameter* param) : FacadeImplementation(param) {
	_initializeImplementation();
}


MigrateStatsSessionImplementation::~MigrateStatsSessionImplementation() {
}


void MigrateStatsSessionImplementation::finalize() {
}

void MigrateStatsSessionImplementation::_initializeImplementation() {
	_setClassHelper(MigrateStatsSessionHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void MigrateStatsSessionImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<MigrateStatsSession*>(stub);
	FacadeImplementation::_setStub(stub);
}

DistributedObjectStub* MigrateStatsSessionImplementation::_getStub() {
	return _this.get();
}

MigrateStatsSessionImplementation::operator const MigrateStatsSession*() {
	return _this.get();
}

void MigrateStatsSessionImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void MigrateStatsSessionImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void MigrateStatsSessionImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void MigrateStatsSessionImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void MigrateStatsSessionImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void MigrateStatsSessionImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void MigrateStatsSessionImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void MigrateStatsSessionImplementation::_serializationHelperMethod() {
	FacadeImplementation::_serializationHelperMethod();

	_setClassName("MigrateStatsSession");

}

void MigrateStatsSessionImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(MigrateStatsSessionImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool MigrateStatsSessionImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (FacadeImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x5f6802ec: //MigrateStatsSession.creature
		TypeInfo<ManagedWeakReference<CreatureObject* > >::parseFromBinaryStream(&creature, stream);
		return true;

	case 0x7e13fcd3: //MigrateStatsSession.attributesToModify
		TypeInfo<Vector<int> >::parseFromBinaryStream(&attributesToModify, stream);
		return true;

	}

	return false;
}

void MigrateStatsSessionImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = MigrateStatsSessionImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int MigrateStatsSessionImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = FacadeImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x5f6802ec; //MigrateStatsSession.creature
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<CreatureObject* > >::toBinaryStream(&creature, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7e13fcd3; //MigrateStatsSession.attributesToModify
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<int> >::toBinaryStream(&attributesToModify, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

MigrateStatsSessionImplementation::MigrateStatsSessionImplementation(CreatureObject* parent) {
	_initializeImplementation();
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		creature = parent;
	creature = parent;
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		Logger.setLoggingName("MigrateStatsSession");
	Logger::setLoggingName("MigrateStatsSession");
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		Logger.setLogging(false);
	Logger::setLogging(false);
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		}
	for (	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		for (int i = 0;
	int i = 0;
	i < 9;
i = i + 1) {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			attributesToModify.add(0);
	(&attributesToModify)->add(0);
}
}

int MigrateStatsSessionImplementation::initializeSession() {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		return 0;
	return 0;
}

int MigrateStatsSessionImplementation::cancelSession() {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		CreatureObject creo = creature;
	ManagedReference<CreatureObject* > creo = creature;
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		return 
	if (creo != NULL){
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			creo.dropActiveSession(SessionFacadeType.MIGRATESTATS);
	creo->dropActiveSession(SessionFacadeType::MIGRATESTATS);
}
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		return 0;
	return 0;
}

int MigrateStatsSessionImplementation::clearSession() {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		attributesToModify.removeAll();
	(&attributesToModify)->removeAll();
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		return 0;
	return 0;
}

int MigrateStatsSessionImplementation::getAttributeToModifyCount() {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		return attributesToModify.size();
	return (&attributesToModify)->size();
}

void MigrateStatsSessionImplementation::setAttributeToModify(int attribute, int value) {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		attributesToModify.set(attribute, value);
	(&attributesToModify)->set(attribute, value);
}

int MigrateStatsSessionImplementation::getAttribtueToModify(int attribute) {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		return attributesToModify.get(attribute);
	return (&attributesToModify)->get(attribute);
}

void MigrateStatsSessionImplementation::migrateStats() {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		CreatureObject creo = creature;
	ManagedReference<CreatureObject* > creo = creature;
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		for 
	if (creo == NULL){
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			cancelSession();
	cancelSession();
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			return;
	return;
}
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		}
	for (	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		for (int i = 0;
	int i = 0;
	i < 9;
i = i + 1) {
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			int newValue = attributesToModify.get(i);
	int newValue = (&attributesToModify)->get(i);
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			int originalAmount = creo.getBaseHAM(i);
	int originalAmount = creo->getBaseHAM(i);
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			creo.setBaseHAM(i, newValue);
	creo->setBaseHAM(i, newValue);
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			creo.setHAM(i, creo.getHAM(i) + (newValue - originalAmount));
	creo->setHAM(i, creo->getHAM(i) + (newValue - originalAmount));
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  			creo.setMaxHAM(i, creo.getMaxHAM(i) + (newValue - originalAmount));
	creo->setMaxHAM(i, creo->getMaxHAM(i) + (newValue - originalAmount));
}
	// server/zone/objects/player/sessions/MigrateStatsSession.idl():  		cancelSession();
	cancelSession();
}

/*
 *	MigrateStatsSessionAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


MigrateStatsSessionAdapter::MigrateStatsSessionAdapter(MigrateStatsSession* obj) : FacadeAdapter(obj) {
}

void MigrateStatsSessionAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_INITIALIZESESSION__:
		{
			
			int _m_res = initializeSession();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_CANCELSESSION__:
		{
			
			int _m_res = cancelSession();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_CLEARSESSION__:
		{
			
			int _m_res = clearSession();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_GETATTRIBUTETOMODIFYCOUNT__:
		{
			
			int _m_res = getAttributeToModifyCount();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETATTRIBUTETOMODIFY__INT_INT_:
		{
			int attribute = inv->getSignedIntParameter();
			int value = inv->getSignedIntParameter();
			
			setAttributeToModify(attribute, value);
			
		}
		break;
	case RPC_GETATTRIBTUETOMODIFY__INT_:
		{
			int attribute = inv->getSignedIntParameter();
			
			int _m_res = getAttribtueToModify(attribute);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_MIGRATESTATS__:
		{
			
			migrateStats();
			
		}
		break;
	default:
		FacadeAdapter::invokeMethod(methid, inv);
	}
}

int MigrateStatsSessionAdapter::initializeSession() {
	return (static_cast<MigrateStatsSession*>(stub))->initializeSession();
}

int MigrateStatsSessionAdapter::cancelSession() {
	return (static_cast<MigrateStatsSession*>(stub))->cancelSession();
}

int MigrateStatsSessionAdapter::clearSession() {
	return (static_cast<MigrateStatsSession*>(stub))->clearSession();
}

int MigrateStatsSessionAdapter::getAttributeToModifyCount() {
	return (static_cast<MigrateStatsSession*>(stub))->getAttributeToModifyCount();
}

void MigrateStatsSessionAdapter::setAttributeToModify(int attribute, int value) {
	(static_cast<MigrateStatsSession*>(stub))->setAttributeToModify(attribute, value);
}

int MigrateStatsSessionAdapter::getAttribtueToModify(int attribute) {
	return (static_cast<MigrateStatsSession*>(stub))->getAttribtueToModify(attribute);
}

void MigrateStatsSessionAdapter::migrateStats() {
	(static_cast<MigrateStatsSession*>(stub))->migrateStats();
}

/*
 *	MigrateStatsSessionHelper
 */

MigrateStatsSessionHelper* MigrateStatsSessionHelper::staticInitializer = MigrateStatsSessionHelper::instance();

MigrateStatsSessionHelper::MigrateStatsSessionHelper() {
	className = "MigrateStatsSession";

	Core::getObjectBroker()->registerClass(className, this);
}

void MigrateStatsSessionHelper::finalizeHelper() {
	MigrateStatsSessionHelper::finalize();
}

DistributedObject* MigrateStatsSessionHelper::instantiateObject() {
	return new MigrateStatsSession(DummyConstructorParameter::instance());
}

DistributedObjectServant* MigrateStatsSessionHelper::instantiateServant() {
	return new MigrateStatsSessionImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* MigrateStatsSessionHelper::instantiatePOD() {
	return new MigrateStatsSessionPOD();
}

DistributedObjectAdapter* MigrateStatsSessionHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new MigrateStatsSessionAdapter(static_cast<MigrateStatsSession*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	MigrateStatsSessionPOD
 */

MigrateStatsSessionPOD::~MigrateStatsSessionPOD() {
}

MigrateStatsSessionPOD::MigrateStatsSessionPOD(void) {
	_className = "MigrateStatsSession";
}


void MigrateStatsSessionPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = MigrateStatsSessionPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int MigrateStatsSessionPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = FacadePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (creature) {
	_nameHashCode = 0x5f6802ec; //MigrateStatsSession.creature
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<CreatureObjectPOD* > >::toBinaryStream(&creature.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (attributesToModify) {
	_nameHashCode = 0x7e13fcd3; //MigrateStatsSession.attributesToModify
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<int> >::toBinaryStream(&attributesToModify.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool MigrateStatsSessionPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (FacadePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x5f6802ec: //MigrateStatsSession.creature
		{
			ManagedWeakReference<CreatureObjectPOD* > _mncreature;
			TypeInfo<ManagedWeakReference<CreatureObjectPOD* > >::parseFromBinaryStream(&_mncreature, stream);
			creature = std::move(_mncreature);
		}
		return true;

	case 0x7e13fcd3: //MigrateStatsSession.attributesToModify
		{
			Vector<int> _mnattributesToModify;
			TypeInfo<Vector<int> >::parseFromBinaryStream(&_mnattributesToModify, stream);
			attributesToModify = std::move(_mnattributesToModify);
		}
		return true;

	}

	return false;
}

void MigrateStatsSessionPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(MigrateStatsSessionPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void MigrateStatsSessionPOD::writeObjectCompact(ObjectOutputStream* stream) {
	FacadePOD::writeObjectCompact(stream);

	TypeInfo<ManagedWeakReference<CreatureObjectPOD* > >::toBinaryStream(&creature.value(), stream);

	TypeInfo<Vector<int> >::toBinaryStream(&attributesToModify.value(), stream);


}

