/*
 *	autogen/server/zone/objects/area/SpawnAreaObserver.cpp generated by engine3 IDL compiler 0.70
 */

#include "SpawnAreaObserver.h"

#include "server/zone/objects/area/SpawnArea.h"

/*
 *	SpawnAreaObserverStub
 */

enum {RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_ = 3913239956};

SpawnAreaObserver::SpawnAreaObserver(SpawnArea* area) : Observer(DummyConstructorParameter::instance()) {
	SpawnAreaObserverImplementation* _implementation = new SpawnAreaObserverImplementation(area);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SpawnAreaObserver");
}

SpawnAreaObserver::SpawnAreaObserver(DummyConstructorParameter* param) : Observer(param) {
	_setClassName("SpawnAreaObserver");
}

SpawnAreaObserver::~SpawnAreaObserver() {
}



int SpawnAreaObserver::notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2) {
	SpawnAreaObserverImplementation* _implementation = static_cast<SpawnAreaObserverImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_);
		method.addUnsignedIntParameter(eventType);
		method.addObjectParameter(observable);
		method.addObjectParameter(arg1);
		method.addSignedLongParameter(arg2);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->notifyObserverEvent(eventType, observable, arg1, arg2);
	}
}

DistributedObjectServant* SpawnAreaObserver::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SpawnAreaObserver::_getImplementationForRead() const {
	return _impl;
}

void SpawnAreaObserver::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SpawnAreaObserverImplementation
 */

SpawnAreaObserverImplementation::SpawnAreaObserverImplementation(DummyConstructorParameter* param) : ObserverImplementation(param) {
	_initializeImplementation();
}


SpawnAreaObserverImplementation::~SpawnAreaObserverImplementation() {
}


void SpawnAreaObserverImplementation::finalize() {
}

void SpawnAreaObserverImplementation::_initializeImplementation() {
	_setClassHelper(SpawnAreaObserverHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SpawnAreaObserverImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SpawnAreaObserver*>(stub);
	ObserverImplementation::_setStub(stub);
}

DistributedObjectStub* SpawnAreaObserverImplementation::_getStub() {
	return _this.get();
}

SpawnAreaObserverImplementation::operator const SpawnAreaObserver*() {
	return _this.get();
}

void SpawnAreaObserverImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SpawnAreaObserverImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SpawnAreaObserverImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SpawnAreaObserverImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SpawnAreaObserverImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SpawnAreaObserverImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SpawnAreaObserverImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SpawnAreaObserverImplementation::_serializationHelperMethod() {
	ObserverImplementation::_serializationHelperMethod();

	_setClassName("SpawnAreaObserver");

}

void SpawnAreaObserverImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpawnAreaObserverImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SpawnAreaObserverImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ObserverImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x455b3429: //SpawnAreaObserver.spawnArea
		TypeInfo<ManagedWeakReference<SpawnArea* > >::parseFromBinaryStream(&spawnArea, stream);
		return true;

	}

	return false;
}

void SpawnAreaObserverImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpawnAreaObserverImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpawnAreaObserverImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ObserverImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x455b3429; //SpawnAreaObserver.spawnArea
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<SpawnArea* > >::toBinaryStream(&spawnArea, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void SpawnAreaObserverImplementation::writeJSON(nlohmann::json& j) {
	ObserverImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["spawnArea"] = spawnArea;

	j["SpawnAreaObserver"] = thisObject;
}

SpawnAreaObserverImplementation::SpawnAreaObserverImplementation(SpawnArea* area) {
	_initializeImplementation();
	// server/zone/objects/area/SpawnAreaObserver.idl():  		spawnArea = area;
	spawnArea = area;
	// server/zone/objects/area/SpawnAreaObserver.idl():  		Logger.setLoggingName("SpawnAreaObserver");
	Logger::setLoggingName("SpawnAreaObserver");
}

int SpawnAreaObserverImplementation::notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2) {
	// server/zone/objects/area/SpawnAreaObserver.idl():  		SpawnArea area = spawnArea;
	ManagedReference<SpawnArea* > area = spawnArea;
	// server/zone/objects/area/SpawnAreaObserver.idl():  			return area.notifyObserverEvent(eventType, observable, arg1, arg2);
	if (area == NULL)	// server/zone/objects/area/SpawnAreaObserver.idl():  			return 1;
	return 1;

	else 	// server/zone/objects/area/SpawnAreaObserver.idl():  			return area.notifyObserverEvent(eventType, observable, arg1, arg2);
	return area->notifyObserverEvent(eventType, observable, arg1, arg2);
}

/*
 *	SpawnAreaObserverAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SpawnAreaObserverAdapter::SpawnAreaObserverAdapter(SpawnAreaObserver* obj) : ObserverAdapter(obj) {
}

void SpawnAreaObserverAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_:
		{
			unsigned int eventType = inv->getUnsignedIntParameter();
			Observable* observable = static_cast<Observable*>(inv->getObjectParameter());
			ManagedObject* arg1 = static_cast<ManagedObject*>(inv->getObjectParameter());
			long long arg2 = inv->getSignedLongParameter();
			
			int _m_res = notifyObserverEvent(eventType, observable, arg1, arg2);
			resp->insertSignedInt(_m_res);
		}
		break;
	default:
		ObserverAdapter::invokeMethod(methid, inv);
	}
}

int SpawnAreaObserverAdapter::notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2) {
	return (static_cast<SpawnAreaObserver*>(stub))->notifyObserverEvent(eventType, observable, arg1, arg2);
}

/*
 *	SpawnAreaObserverHelper
 */

SpawnAreaObserverHelper* SpawnAreaObserverHelper::staticInitializer = SpawnAreaObserverHelper::instance();

SpawnAreaObserverHelper::SpawnAreaObserverHelper() {
	className = "SpawnAreaObserver";

	Core::getObjectBroker()->registerClass(className, this);
}

void SpawnAreaObserverHelper::finalizeHelper() {
	SpawnAreaObserverHelper::finalize();
}

DistributedObject* SpawnAreaObserverHelper::instantiateObject() {
	return new SpawnAreaObserver(DummyConstructorParameter::instance());
}

DistributedObjectServant* SpawnAreaObserverHelper::instantiateServant() {
	return new SpawnAreaObserverImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* SpawnAreaObserverHelper::instantiatePOD() {
	return new SpawnAreaObserverPOD();
}

DistributedObjectAdapter* SpawnAreaObserverHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SpawnAreaObserverAdapter(static_cast<SpawnAreaObserver*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SpawnAreaObserverPOD
 */

SpawnAreaObserverPOD::~SpawnAreaObserverPOD() {
}

SpawnAreaObserverPOD::SpawnAreaObserverPOD(void) {
	_className = "SpawnAreaObserver";
}


void SpawnAreaObserverPOD::writeJSON(nlohmann::json& j) {
	ObserverPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (spawnArea)
		thisObject["spawnArea"] = spawnArea.value();

	j["SpawnAreaObserver"] = thisObject;
}


void SpawnAreaObserverPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpawnAreaObserverPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpawnAreaObserverPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ObserverPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (spawnArea) {
	_nameHashCode = 0x455b3429; //SpawnAreaObserver.spawnArea
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<SpawnAreaPOD* > >::toBinaryStream(&spawnArea.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool SpawnAreaObserverPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ObserverPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x455b3429: //SpawnAreaObserver.spawnArea
		{
			ManagedWeakReference<SpawnAreaPOD* > _mnspawnArea;
			TypeInfo<ManagedWeakReference<SpawnAreaPOD* > >::parseFromBinaryStream(&_mnspawnArea, stream);
			spawnArea = std::move(_mnspawnArea);
		}
		return true;

	}

	return false;
}

void SpawnAreaObserverPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpawnAreaObserverPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SpawnAreaObserverPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ObserverPOD::writeObjectCompact(stream);

	TypeInfo<ManagedWeakReference<SpawnAreaPOD* > >::toBinaryStream(&spawnArea.value(), stream);


}

