/*
 *	autogen/server/zone/objects/creature/conversation/InformantMissionConversationObserver.h generated by engine3 IDL compiler 0.70
 */

#ifndef INFORMANTMISSIONCONVERSATIONOBSERVER_H_
#define INFORMANTMISSIONCONVERSATIONOBSERVER_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "server/zone/objects/creature/conversation/ConversationObserver.h"

#include "server/zone/objects/creature/conversation/screenhandlers/InformantMissionScreenHandler.h"

namespace server {
namespace zone {
namespace objects {
namespace creature {
namespace conversation {

class InformantMissionConversationObserver : public ConversationObserver {
public:
	InformantMissionConversationObserver(unsigned int convoTemplateCRC);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	InformantMissionConversationObserver(DummyConstructorParameter* param);

	virtual ~InformantMissionConversationObserver();

	friend class InformantMissionConversationObserverHelper;
};

} // namespace conversation
} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature::conversation;

namespace server {
namespace zone {
namespace objects {
namespace creature {
namespace conversation {

class InformantMissionConversationObserverImplementation : public ConversationObserverImplementation {
	InformantMissionScreenHandler informantMissionScreenHandler;

public:
	InformantMissionConversationObserverImplementation(unsigned int convoTemplateCRC);

	InformantMissionConversationObserverImplementation(DummyConstructorParameter* param);

	WeakReference<InformantMissionConversationObserver*> _this;

	operator const InformantMissionConversationObserver*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~InformantMissionConversationObserverImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class InformantMissionConversationObserver;
};

class InformantMissionConversationObserverAdapter : public ConversationObserverAdapter {
public:
	InformantMissionConversationObserverAdapter(InformantMissionConversationObserver* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class InformantMissionConversationObserverHelper : public DistributedObjectClassHelper, public Singleton<InformantMissionConversationObserverHelper> {
	static InformantMissionConversationObserverHelper* staticInitializer;

public:
	InformantMissionConversationObserverHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<InformantMissionConversationObserverHelper>;
};

} // namespace conversation
} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature::conversation;

namespace server {
namespace zone {
namespace objects {
namespace creature {
namespace conversation {

class InformantMissionConversationObserverPOD : public ConversationObserverPOD {
public:
	Optional<InformantMissionScreenHandler> informantMissionScreenHandler;

	String _className;
	InformantMissionConversationObserverPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~InformantMissionConversationObserverPOD();

};

} // namespace conversation
} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature::conversation;

#endif /*INFORMANTMISSIONCONVERSATIONOBSERVERPOD_H_*/
